const Top100 = [
  { name: 'Activision Blizzard',
    symbol: 'ATVI' },
  { name: 'Adobe Systems Incorporated',
    symbol: 'ADBE'},
  { name: 'Alexion Pharmaceuticals',
    symbol: 'ALXN'},
  { name: 'Align Technology, Inc',
    symbol: 'ALGN'},
  { name: 'Alphabet Inc. Class A',
    symbol: 'OOGL'},
  { name: 'Alphabet Inc. Class C',
    symbol: 'GOOG'},
  { name: 'Amazon.com, Inc.',
    symbol: 'AMZN'},
  { name: 'American Airlines Group',
    symbol: 'AAL'},
  { name: 'Amgen Inc.',
    symbol: 'AMGN'},
  { name: 'Analog Devices',
    symbol: 'ADI'},
  { name: 'Apple Inc. ',
    symbol: 'AAPL'},
  { name: 'Applied Materials, Inc.',
    symbol: 'AMAT'},
  { name: 'ASML Holding',
    symbol: 'ASML'},
  { name: 'Autodesk, Inc.',
    symbol: 'ADSK'},
  { name: 'Automatic Data Processing, Inc.',
    symbol: 'ADP'},
  { name: 'Baidu.com, Inc.',
    symbol: 'BIDU'},
  { name: 'Biogen, Inc',
    symbol: 'BIIB'},
  { name: 'BioMarin Pharmaceutical, Inc.',
    symbol: 'BMRN'},
  { name: 'Booking Holdings',
    symbol: 'BKNG'},
  { name: 'Broadcom Inc.',
    symbol: 'AVGO'},
  { name: 'CA Technologie',
    symbol: 'CA'},
  { name: 'Cadence Design Systems, Inc.',
    symbol: 'CDNS'},
  { name: 'Celgene Corporation',
    symbol: 'CELG'},
  { name: 'Cerner Corporation',
    symbol: 'CERN'},
  { name: 'Charter Communications, Inc.',
    symbol: 'CHTR'},
  { name: 'Check Point Software Technologies Ltd.',
    symbol: 'CHKP'},
  { name: 'Cintas Corporation',
    symbol: 'CTAS'},
  { name: 'Cisco Systems, Inc.',
    symbol: 'CSCO'},
  { name: 'Citrix Systems, Inc.',
    symbol: 'CTXS'},
  { name: 'Cognizant Technology Solutions Corporation',
    symbol: 'CTSH'},
  { name: 'Comcast Corporation',
    symbol: 'MCSA'},
  { name: 'Costco Wholesale Corporation',
    symbol: 'COST'},
  { name: 'CSX Corporation',
    symbol: 'CSX'},
  { name: 'Ctrip International',
    symbol: 'CTRP'},
  { name: 'Dentsply Sirona',
    symbol: 'XRAY'},
  { name: 'Dollar Tree, Inc.',
    symbol: 'DLTR'},
  { name: 'eBay Inc.',
    symbol: 'EBAY'},
  { name: 'Electronic Art',
    symbol: 'EA'},
  { name: 'Expedia Group',
    symbol: 'EXPE'},
  { name: 'Express Scripts, Inc.',
    symbol: 'ESRX'},
  { name: 'Facebook, Inc',
    symbol: 'FB'},
  { name: 'Fastenal Company',
    symbol: 'FAST'},
  { name: 'Fiserv, Inc.',
    symbol: 'FISV'},
  { name: 'Gilead Sciences, Inc.',
    symbol: 'GILD'},
  { name: 'Hasbro, Inc.',
    symbol: 'HAS'},
  { name: 'Henry Schein, Inc.',
    symbol: 'HSIC'},
  { name: 'Hologic, Inc.',
    symbol: 'HOLX'},
  { name: 'IDEXX Laboratories, Inc.',
    symbol: 'IDXX'},
  { name: 'Illumina, Inc.',
    symbol: 'ILMN'},
  { name: 'Incyte Corporation',
    symbol: 'INCY'},
  { name: 'Intel Corporation',
    symbol: 'INTC'},
  { name: 'Intuit, Inc.',
    symbol: 'INTU'},
  { name: 'Intuitive Surgical Inc.',
    symbol: 'ISRG'},
  { name: 'J.B. Hunt Transport Services, Inc.',
    symbol: 'JBHT'},
  { name: 'JD.co',
    symbol: 'JD'},
  { name: 'KLA-Tencor Corporation',
    symbol: 'KLAC'},
  { name: 'Lam Research, Inc.',
    symbol: 'LRCX'},
  { name: 'Liberty Global plc Ordinary A',
    symbol: 'BTYA'},
  { name: 'Liberty Global plc Ordinary C',
    symbol: 'BTYK'},
  { name: 'Marriott International, Inc.',
    symbol: '(MAR'},
  { name: 'Maxim Integrated Products',
    symbol: 'MXIM'},
  { name: 'MercadoLibre',
    symbol: 'MELI'},
  { name: 'Microchip Technology',
    symbol: 'MCHP'},
  { name: 'Micron Technology, Inc',
    symbol: 'MU'},
  { name: 'Microsoft Corporation',
    symbol: 'MSFT'},
  { name: 'Mondelēz International',
    symbol: 'MDLZ'},
  { name: 'Monster Beverage',
    symbol: 'MNST'},
  { name: 'Mylan N.V.',
    symbol: 'MYL'},
  { name: 'NetEase, Inc.',
    symbol: 'NTES'},
  { name: 'Netflix',
    symbol: 'NFLX'},
  { name: 'NVIDIA Corporation',
    symbol: 'NVDA'},
  { name: 'O\'Reilly Automotive, Inc.',
    symbol: 'ORLY'},
  { name: 'PACCAR Inc.',
    symbol: 'PCAR'},
  { name: 'Paychex, Inc.',
    symbol: 'PAYX'},
  { name: 'PayPal Holdings, Inc.',
    symbol: 'PYPL'},
  { name: 'PepsiCo, Inc.',
    symbol: 'PEP'},
  { name: 'QUALCOMM Incorporated',
    symbol: 'QCOM'},
  { name: 'Qurate Retail Group',
    symbol: 'RTEA'},
  { name: 'Regeneron Pharmaceuticals',
    symbol: 'REGN'},
  { name: 'Ross Stores Inc.',
    symbol: 'ROST'},
  { name: 'Seagate Technology Holdings',
    symbol: 'STX'},
  { name: 'Shire plc',
    symbol: 'SHPG'},
  { name: 'Sirius XM Radio, Inc.',
    symbol: 'SIRI'},
  { name: 'Skyworks Solutions, Inc.',
    symbol: 'SWKS'},
  { name: 'Starbucks Corporation',
    symbol: 'SBUX'},
  { name: 'Symantec Corporation',
    symbol: 'SYMC'},
  { name: 'Synopsys, Inc.',
    symbol: 'SNPS'},
  { name: 'T-Mobile US',
    symbol: 'TMUS'},
  { name: 'Take-Two Interactive, Inc.',
    symbol: 'TTWO'},
  { name: 'Tesla, Inc.',
    symbol: 'TSLA'},
  { name: 'Texas Instruments, Inc.',
    symbol: 'TXN'},
  { name: 'The Kraft Heinz Company',
    symbol: 'KHC'},
  { name: 'Twenty-First Century Fox Class A',
    symbol: 'FOXA'},
  { name: 'Twenty-First Century Fox Class B',
    symbol: 'FOX'},
  { name: 'Ulta Beauty',
    symbol: 'ULTA'},
  { name: 'Verisk Analytics',
    symbol: 'VRSK'},
  { name: 'Vertex Pharmaceuticals',
    symbol: 'VRTX'},
  { name: 'Vodafone Group, plc.',
    symbol: 'VOD'},
  { name: 'Walgreens Boots Alliance',
    symbol: 'WBA'},
  { name: 'Western Digital',
    symbol: 'WDC'},
  { name: 'Workday, Inc.',
    symbol: 'WDAY'},
  { name: 'Wynn Resorts',
    symbol: 'WYNN'},
  { name: 'Xilinx, Inc.',
    symbol: 'XLNX'},
];